module.exports = `
  type Event {
    _id: String
    name: String
    date: String
    money: String
    text: String
    user: User!
  }

  type User {
    _id: String
    name: String
    email: String!
    jwt: String
    events: [Event]
  }

  type Query {
    allEvents: [Event]
    event(_id:String!):Event
    allUsers: [User]
  }

  type Mutation {
    addEvent(
      name: String
      date: String
      money: String
      text: String
    ):Event
    updateEvent(
      _id: String
      name: String
      date: String
      money: String
      text: String
    ):Event
    deleteEvent(
      _id: String
    ):Event
    register(
      email: String!
      password: String!
      name: String!
    ):User
    login(
      email: String!
      password: String!
    ):User
  }
`


